apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dgraph-api-deployment
spec:
  selector:
    matchLabels:
      app: dgraph-api
  replicas: 1
  template:
    metadata:
      labels:
        app: dgraph-api
    spec:
      containers:
      - name: dgraph-api
        image: gcr.io/spy-crowd/dgraph-api:v0.9.0
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.2"
        ports:
        - containerPort: 50051
