apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: neo4j-api-deployment
spec:
  selector:
    matchLabels:
      app: neo4j-api
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j-api
    spec:
      containers:
      - name: neo4j-api
        image: gcr.io/spy-crowd/neo4j-api:v0.9.0
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.2"
        ports:
        - containerPort: 5000
